---
title: "Etosha Heights Vegetation Prediction from Surface Reflectance"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE, echo = F, message = F}
knitr::opts_chunk$set(echo = TRUE)
library(terra)
library(tidyverse)
library(patchwork)
library(caret)
library(randomForest)
```


```{r, echo = F, message = F, warning = F}
rm(list = ls())

#------------------------ fit a random forest model to each surface reflectance mosaic ----------------------#
# list all surface reflectance mosaics
srf <- list.files(path = "L:/projects/etosha_heights/eh_planet/sr_resample/", 
                  pattern = glob2rx("EH*8b*sr*composite_resample.tif"), 
                  recursive = T, 
                  full.names = T)

# read in the first as a reference
d <- rast(srf[1])

# read and cleanup veg data
veg.p <- project(vect("L:/projects/etosha_heights/eh_veg_data/DB_EtoshaHeights_VegTransects_5m_buffer.shp"),d)[,1:3]
names(veg.p) <- c("assoc", "class", "releve")
veg.p$ID <- 1:nrow(veg.p) # add an ID column

# create an empty list for rf model outputs
rf_out <- list()

# loop through each file and fit a model
for(i in 1:length(srf))
{
  # read in the reflectance file
  d <- rast(srf[i])
  
  # simplify band names
  names(d) <- paste("B", 1:8, sep = "")
  
  # extract pixel values
  sr <- terra::extract(d, veg.p, FUN = NULL)
  
  # join with other variables from veg.p
  psr <- full_join(sr, as.data.frame(veg.p)) %>%
    na.omit()
  rm(sr)
  
  rec <- nrow(psr)
  # specify training and validation data sets
  set.seed(11213)

  # randomly select half of the records
  sampleSamp <- sample(seq(1,rec),rec/2)
  
  psr$sampleType <- "train"
  
  psr$sampleType[sampleSamp] <- "valid"


  # create training and validation subsets
  trainD <- psr[psr$sampleType=="train",]
  validD<- psr[psr$sampleType=="valid",]
  
  #------------Random Forest Classification of reflectance data------------#
  # run the Random Forest model
  tc <- trainControl(method = "repeatedcv", # repeated cross-validation of the training data
                     number = 10, # number 10 fold
                     repeats = 10) # number of repeats
  ###random forests
  #Typically square root of number of variables
  rf.grid <- expand.grid(mtry=1:3) # number of variables available for splitting at each tree node
  
  rf_model <- caret::train(x = trainD[,2:9], #digital number data
                           y = as.factor(trainD$assoc), #land class we want to predict
                           method = "rf", #use random forest
                           metric="Accuracy", #assess by accuracy
                           trControl = tc, #use parameter tuning method
                           tuneGrid = rf.grid) #parameter tuning grid
  
  
  rf_out[[i]] <- confusionMatrix(predict(rf_model,validD[,2:9]),as.factor(validD$assoc))
}

rf_ovr <- rf_out[[1]]$overall

for(i in 2:length(rf_out))
{
  rf_ovr <- rbind(rf_ovr,rf_out[[i]]$overall )
}



```



```{r pressure, echo=FALSE}
plot(pressure)
```


